[build]
builder = "dockerfile"

[deploy]
startCommand = "python -c \"import os; from app import app; app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 5000)))\""
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"