services:
  - type: web
    name: quickkart
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_MAPS_API_KEY
        sync: false  # You'll set this in Render dashboard